### ISSUE TITLE
 panic serving 127.0.0.1:56674: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mschaaf** [sentriz/gonic#239]
get this exception on playing songs.
client dsub
album consists of 10 flac files with id3 tags
gonic 0.14.0 latest

dsub shows the file as title.
refresh corrects issue 
```
Sep 18 09:17:03  gonic[297677]: 2022/09/18 09:17:03 http: panic serving 127.0.0.1:56674: runtime error: invalid memory address or nil pointer dereference
Sep 18 09:17:03  gonic[297677]: goroutine 160473 [running]:
Sep 18 09:17:03  gonic[297677]: net/http.(*conn).serve.func1(0xc0004c6e60)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:1804 +0x153
Sep 18 09:17:03  gonic[297677]: panic(0xb69300, 0x10b74f0)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/runtime/panic.go:971 +0x499
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).ServeStream(0xc00019fef0, 0xd55140, 0xc0005aaac8, 0xc0003a3000, 0x0)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlsubsonic/handlers_raw.go:221 +0x470
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).HR.func1(0xd55140, 0xc0005aaac8, 0xc0003a3000)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlsubsonic/ctrl.go:109 +0x47
Sep 18 09:17:03  gonic[297677]: net/http.HandlerFunc.ServeHTTP(0xc000468c60, 0xd55140, 0xc0005aaac8, 0xc0003a3000)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithUser.func1(0xd55140, 0xc0005aaac8, 0xc0003a2f00)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlsubsonic/middleware.go:87 +0x6ac
Sep 18 09:17:03  gonic[297677]: net/http.HandlerFunc.ServeHTTP(0xc000166940, 0xd55140, 0xc0005aaac8, 0xc0003a2f00)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithRequiredParams.func1(0xd55140, 0xc0005aaac8, 0xc0003a2f00)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlsubsonic/middleware.go:50 +0x1c5
Sep 18 09:17:03  gonic[297677]: net/http.HandlerFunc.ServeHTTP(0xc00046fda0, 0xd55140, 0xc0005aaac8, 0xc0003a2f00)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithParams.func1(0xd55140, 0xc0005aaac8, 0xc0003a2e00)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlsubsonic/middleware.go:33 +0x187
Sep 18 09:17:03  gonic[297677]: net/http.HandlerFunc.ServeHTTP(0xc0005aaa80, 0xd55140, 0xc0005aaac8, 0xc0003a2e00)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlbase.(*Controller).WithCORS.func1(0xd55140, 0xc0005aaac8, 0xc0003a2e00)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlbase/ctrl.go:88 +0x315
Sep 18 09:17:03  gonic[297677]: net/http.HandlerFunc.ServeHTTP(0xc0005aaa98, 0xd55140, 0xc0005aaac8, 0xc0003a2e00)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Sep 18 09:17:03  gonic[297677]: go.senan.xyz/gonic/server/ctrlbase.(*Controller).WithLogging.func1(0xd555f0, 0xc00062a7e0, 0xc0003a2e00)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/go.senan.xyz/gonic@v0.14.0/server/ctrlbase/ctrl.go:65 +0xa9
Sep 18 09:17:03  gonic[297677]: net/http.HandlerFunc.ServeHTTP(0xc0005aaab0, 0xd555f0, 0xc00062a7e0, 0xc0003a2e00)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2049 +0x44
Sep 18 09:17:03  gonic[297677]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc00010c6c0, 0xd555f0, 0xc00062a7e0, 0xc0003a2c00)
Sep 18 09:17:03  gonic[297677]:         /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
Sep 18 09:17:03  gonic[297677]: net/http.serverHandler.ServeHTTP(0xc0001021c0, 0xd555f0, 0xc00062a7e0, 0xc0003a2c00)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2867 +0xa3
Sep 18 09:17:03  gonic[297677]: net/http.(*conn).serve(0xc0004c6e60, 0xd56e20, 0xc000887040)
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:1932 +0x8cd
Sep 18 09:17:03  gonic[297677]: created by net/http.(*Server).Serve
Sep 18 09:17:03  gonic[297677]:         /media/data/gonic/go/src/net/http/server.go:2993 +0x39b
```

**Comment by sentriz** [comment]
hi! thanks for the issue. this one is already fixed on the master branch (or docker nightly)
hopefully going to be doing a release soon :+1:
