### ISSUE TITLE
stacktrace crash on search

### ISSUE THREAD

**Issue by jrwren** [sentriz/gonic#24]
```
gonic_1  | 2019/12/05 22:33:33 http: panic serving 192.168.15.242:60544: runtime error: invalid memo
ry address or nil pointer dereference
gonic_1  | goroutine 173649 [running]:
gonic_1  | net/http.(*conn).serve.func1(0xc0003481e0)                                               gonic_1  |      /usr/local/go/src/net/http/server.go:1769 +0x139
gonic_1  | panic(0x9cf8e0, 0xef8e00)
gonic_1  |      /usr/local/go/src/runtime/panic.go:522 +0x1b5                                       gonic_1  | senan.xyz/g/gonic/server/ctrlsubsonic/spec.NewTrackByTags(0xc00025cf70, 0xc00015d100, 0x$
0006d8120)
gonic_1  |      /src/server/ctrlsubsonic/spec/construct_by_tags.go:44 +0x28f                        gonic_1  | senan.xyz/g/gonic/server/ctrlsubsonic.(*Controller).ServeSearchThree(0xc0000102f0, 0xc00$
15cb00, 0xc00044fb80)
gonic_1  |      /src/server/ctrlsubsonic/handlers_by_tags.go:210 +0xd0c
gonic_1  | senan.xyz/g/gonic/server/ctrlsubsonic.(*Controller).H.func1(0xb3d600, 0xc000161920, 0xc0$
015cb00)                                                                                            gonic_1  |      /src/server/ctrlsubsonic/ctrl.go:85 +0x33
gonic_1  | net/http.HandlerFunc.ServeHTTP(0xc00038a8f0, 0xb3d600, 0xc000161920, 0xc00015cb00)
gonic_1  |      /usr/local/go/src/net/http/server.go:1995 +0x44
gonic_1  | senan.xyz/g/gonic/server/ctrlsubsonic.(*Controller).WithValidSubsonicArgs.func1(0xb3d600$
 0xc000161920, 0xc00015c900)                                                                        gonic_1  |      /src/server/ctrlsubsonic/middleware.go:78 +0x6e3
gonic_1  | net/http.HandlerFunc.ServeHTTP(0xc0001618a0, 0xb3d600, 0xc000161920, 0xc00015c900)
gonic_1  |      /usr/local/go/src/net/http/server.go:1995 +0x44
gonic_1  | senan.xyz/g/gonic/server/ctrlbase.(*Controller).WithCORS.func1(0xb3d600, 0xc000161920, 0$
c00015c900)                                                                                         gonic_1  |      /src/server/ctrlbase/ctrl.go:75 +0x32a
gonic_1  | net/http.HandlerFunc.ServeHTTP(0xc0001618e0, 0xb3d600, 0xc000161920, 0xc00015c900)
gonic_1  |      /usr/local/go/src/net/http/server.go:1995 +0x44
gonic_1  | senan.xyz/g/gonic/server/ctrlbase.(*Controller).WithLogging.func1(0xb3d580, 0xc00013e620$
 0xc00015c900)                                                                                      gonic_1  |      /src/server/ctrlbase/ctrl.go:58 +0x9d
gonic_1  | net/http.HandlerFunc.ServeHTTP(0xc000161900, 0xb3d580, 0xc00013e620, 0xc00015c900)
gonic_1  |      /usr/local/go/src/net/http/server.go:1995 +0x44
gonic_1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000c66c0, 0xb3d580, 0xc00013e620, 0xc0003$
f800)
gonic_1  |      /go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe3
gonic_1  | net/http.serverHandler.ServeHTTP(0xc000271860, 0xb3d580, 0xc00013e620, 0xc0003df800)
gonic_1  |      /usr/local/go/src/net/http/server.go:2774 +0xa8
gonic_1  | net/http.(*conn).serve(0xc0003481e0, 0xb3e580, 0xc0007d0f40)                             gonic_1  |      /usr/local/go/src/net/http/server.go:1878 +0x851
gonic_1  | created by net/http.(*Server).Serve
gonic_1  |      /usr/local/go/src/net/http/server.go:2884 +0x2f4
gonic_1  | 2019/12/05 22:33:33 response  200  for `/rest/search2.view?u=jrwren&p=enc:6a727772656e676
f6e696370617373&v=1.11.0&c=substreamer&f=json&query=Mentallo&artistCount=1&albumCount=100&songCount=
1`
```

**Comment by sentriz** [comment]
weird. not sure how this could have happened. it means the scanner didn't process a folder completely.
pushed a fix for the panic (currently building on docker hub) but maybe try scan again?

**Comment by jrwren** [comment]
The first scan I did, it did fail with a recursing depth problem. I had a symlink to itself. I deleted that and rescanned and things are fine.
